Models/ErrorViewModel.cs
using System;

namespace WebCrawlerSWD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Jobs.cs
using System;
using System.Collections.Generic;

namespace WebCrawlerSWD.Models
{
    public class Job
    {
        public string CompanyName { get; set; }
        public string JobTitle { get; set; }
        public string Salary { get; set; }
        public string Address { get; set; }
        public string LogoURL { get; set; }

        public Job(String CompanyName, String JobTitle, String Salary, String Address, String LogoURL)
        {
            this.CompanyName = CompanyName;
            this.JobTitle = JobTitle;
            this.Salary = Salary;
            this.Address = Address;
            this.LogoURL = LogoURL;
        }

    }

    public class JobsByExp
    {
        public List<Job> Jobs = new();
        public string TotalJobsByExpFound { get; set; }
        public string ExpCategory { get; set; }

        public JobsByExp()
        {
            Jobs = new List<Job>();
            TotalJobsByExpFound = "0";
            ExpCategory = "All";
        }
    }

    public class JobsMangement
    {
        public List<JobsByExp> ListJob = new();
        public string TotalJobs { get; set; }
        public string JobType { get; set; }

        public JobsMangement()
        {
            if (ListJob == null)
            {
                ListJob = new List<JobsByExp>();
            }      
            TotalJobs = "0";
            JobType = "";
        }
    }

    public class JobsChart
    {
        public List<int> ListJobChart { get; set; }

        public JobsChart()
        {
            ListJobChart = new();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebCrawlerSWD.Models;

namespace WebCrawlerSWD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SpiderController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using WebCrawlerSWD.ConstURL;
using WebCrawlerSWD.Models;
using WebCrawlerSWD.SpiderBot;

namespace WebCrawlerSWD.Controllers
{
    public class SpiderController : Controller
    {
        private static JobsMangement JobMng = new();

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult StartCrawling()
        {
            JobMng = new();
            var ListUrl = new WebURL().GetUrlLinks();
            Spider spider = new();

            spider.StartCrawlingAsync(JobMng, ListUrl);
            
            return PartialView("_StartCrawling", JobMng);
        }

        public ActionResult ShowJob()
        {
            JobMng = new();
            var ListUrl = new WebURL().GetUrlLinks();
            Spider spider = new();

            spider.StartCrawlingAsync(JobMng, ListUrl);

            JobScheduler.Start();

            return PartialView("_StartCrawling", JobMng);
        }

        public ActionResult StopJob()
        {
            JobScheduler.Stop();
            return PartialView("StopJob", JobMng);
        }

        public ActionResult ShowChart()
        {
            if (JobMng == null)
            {
                JobMng = new JobsMangement();
                var ListUrl = new WebURL().GetUrlLinks();
                Spider spider = new();

                spider.StartCrawlingAsync(JobMng, ListUrl);
            }

            JobsChart numberJobs = new();

            for(int i = 1; i < JobMng.ListJob.Count; i++)
            {
                numberJobs.ListJobChart.Add(int.Parse(JobMng.ListJob[i].TotalJobsByExpFound.Replace(",","")));
            }

            return PartialView("ShowChart", numberJobs);
        }

        public ActionResult ViewDetails(string expCategory)
        {
            foreach(var job in JobMng.ListJob)
            {
                if(job.ExpCategory == expCategory)
                {
                    return View(job);
                }
            }
            return View();
        }

        public ActionResult ExportToExcel()
        {
            XLWorkbook wb = new XLWorkbook();

            if (JobMng == null)
            {
                JobMng = new JobsMangement();
                var ListUrl = new WebURL().GetUrlLinks();
                Spider spider = new();

                spider.StartCrawlingAsync(JobMng, ListUrl);
            }
            // Get total jobs summarize
            DataTable dt = new DataTable("Jobs Data Summarize");
            dt.Columns.AddRange(new DataColumn[2] {
                new DataColumn("Experience Advanced Type"),
                new DataColumn("Total Jobs Found")
            });

            var jobs = JobMng.ListJob;

            for(int i = 1; i<jobs.Count; i++)
            {
                dt.Rows.Add(jobs[i].ExpCategory, jobs[i].TotalJobsByExpFound);
            }
            // Get Detail jobs
            DataTable dt2;
            for (int i = 0; i < JobMng.ListJob.Count; i++)
            {
                dt2 = new DataTable("Exp " + JobMng.ListJob[i].ExpCategory.ToString());
                dt2.Columns.AddRange(new DataColumn[4] {
                    new DataColumn("Job Title"),
                    new DataColumn("Company Name"),
                    new DataColumn("Location"),
                    new DataColumn("Salary")
                });
                //Add job exp type
                dt2.Rows.Add(JobMng.ListJob[i].ExpCategory.ToString());

                var jobsDetail = JobMng.ListJob[i].Jobs;
                for (int j = 0; j < jobsDetail.Count; j++)
                {
                    var job = jobsDetail[j];
                    dt2.Rows.Add(job.JobTitle, job.CompanyName, job.Address, job.Salary);
                }               
                wb.Worksheets.Add(dt2);
            }
                wb.Worksheets.Add(dt);
                
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Jobs Data.xlsx");
                }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    body{
        background-image: url('https://wallpapercave.com/wp/wp2608224.jpg');
        background-repeat: no-repeat;
        background-size: cover;
    }

    .welcome-text{
        margin-top: 40%;
        color: white; 
        text-shadow: 2px 2px 5px red;
        font-family: 'Brush Script MT', cursive;
        font-size: 100px;
    }
</style>

<div class="text-center welcome-text">
    <h1 class="display-4"><b>Welcome</b></h1>
    <h3><b>Web Crawler SWD Limited Version</b></h3>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCrawlerSWD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spider" asp-action="Index">Web Crawling</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebCrawlerSWD
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Spider/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<style>
    #result-crawling{
        background-image: url('https://images.unsplash.com/photo-1540270776932-e72e7c2d11cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTl8fHxlbnwwfHx8fA%3D%3D&w=1000&q=80');
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>

    <div class="tool-bar row">
        <p id="start-crawling">
            <a href="#" class="border border-dark btn btn-default"><i class="fa fa-list-alt"></i> Start Crawling</a>
        </p>

        <p id="start-job" style="margin-left:20px">
            <a href="#" class="border border-dark btn btn-default"><i class="fa fa-list-alt"></i> Start Job</a>
        </p>

        <p id="stop-job" style="margin-left:20px">
            <a href="#" class="border border-dark btn btn-default"><i class="fa fa-list-alt"></i> Stop Job</a>
        </p>

        <p id="btn-chart" style="margin-left:20px;">
            <a href="#" class="border border-dark btn btn-default"><i class="fa fa-pie-chart"></i> Show Chart</a>
        </p>

        <div id="div-export" style="margin-left:87.2%">
            <p id="btn-export">
                <a href="#" class="border border-dark btn btn-success"><i class="fa-solid fa-file-export"></i> Export to Excel </a>
            </p>
        </div>
    </div>

<div id="result-crawling">
</div><br/><br/>
<div id="result-chart">
</div>
<div id="result-job">

</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    var isLoad = false; 
    var isJobStarted = false;
    $("#start-crawling").on("click", function () {

    $.ajax({
        url: '@Url.Action("StartCrawling", "Spider")',
            type: 'get',
            datatype: 'html',
            success: function (data) {
                $('#result-crawling').html(data);
                $('#result-chart').html("");
                $('#result-job').html("");
                isLoad = true;
            }
        });

});

$("#start-job").on("click", function(){
    if(isJobStarted==false){
        $.ajax({
        url: '@Url.Action("ShowJob", "Spider")',
            type: 'get',
            datatype: 'html',
            success: function (data) {
                $('#result-crawling').html(data);
                $('#result-chart').html("");
                $('#result-job').html("");
                isLoad = true;
                isJobStarted = true;
            }
        });
    }else{
        alert("Job is already started !!");
    }
    
});

$("#stop-job").on("click", function(){
    if(isJobStarted==true){
        $.ajax({
        url: '@Url.Action("StopJob", "Spider")',
            type: 'get',
            datatype: 'html',
            success: function (data) {
                alert("Spider bot is stopped !")
                isJobStarted = false;
            }
        });
    }else{
        alert("Job is not started !!");
    }
    
});

$("#btn-chart").on("click", function () {
    if(isLoad){
        $.ajax({
        url: '@Url.Action("ShowChart", "Spider")',
            type: 'get',
            datatype: 'html',
            success: function (data) {
                $('#result-chart').html(data);
                $(window).scrollTop($('#pie-chart').offset().top);
            }
        });
    }else{
        alert("No data for chart!");
    }
});

$("#btn-export").on("click",function(){
    if(isLoad){
        window.location.href = '@Url.Action("ExportToExcel", "Spider")';
    }else{
        alert("No data to export!");
    }
});

</script>

Views/Spider/ShowChart.cshtml
@model WebCrawlerSWD.Models.JobsChart
@{
    ViewData["Title"] = "ShowChart";
}

<h1 class="text-center">Jobs Chart</h1>

<div id="chart-jobs" style="width:50%;height:50%;">
    <canvas id="pie-chart"></canvas>
</div>

<script type="text/javascript">
    $(function(){
        var ctx = document.getElementById("pie-chart").getContext('2d');

        var pieChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: ["0 Exp","1 Year Exp Less","1 Year Exp","2 Years Exp","3 Years Exp","4 Years Exp","5 Years Exp","Over 5 Years Exp"],
                datasets: [{
                    backgroundColor:["#2ecc71","#3498db","#95a5a6","9b59b6","#e1e700","#ff0000","#75ede7","#2069e7"],
                    data: [@Model.ListJobChart[0],@Model.ListJobChart[1],@Model.ListJobChart[2],@Model.ListJobChart[3],
                           @Model.ListJobChart[4],@Model.ListJobChart[5],@Model.ListJobChart[6],@Model.ListJobChart[7]]
                }]
            }
        });
    });
</script>
    

Views/Spider/ShowJob.cshtml
@{
    ViewData["Title"] = "ShowJob";
}

<h3 style="color:blueviolet">Crawling Job is Started</h3>
<p>Spider bot will crawling topcv website every 5 minutes.</p>

Views/Spider/StopJob.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h3 style="color:orangered">Crawling Job has Stopped</h3>

Views/Spider/ViewDetails.cshtml
@model WebCrawlerSWD.Models.JobsByExp

@{
    ViewData["Title"] = "ViewDetails";
}

<h3>Experience Advanced: @Model.ExpCategory.ToString()</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                Logo
            </th>
            <th>
                Job Title
            </th>
            <th>
                Company Name
            </th>
            <th>
                Address
            </th>
            <th>
                Salary
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Jobs) {
        <tr>
            <td>
                <img style="height:80px;width:80px;" src="@item.LogoURL" alt="Logo Company"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
        </tr>
}
    </tbody>
</table>

Views/Spider/_StartCrawling.cshtml
@model WebCrawlerSWD.Models.JobsMangement


    <div>
        <b>Job Type: </b> @Model.JobType
    </div>

    <div">
        <b>Total Jobs Found:</b> @Model.TotalJobs
    </div><br/>

<table class="table table-bordered table-striped" style="color:white">
    <thead>
        <tr>
            <th>
                Experience Advanced Type
            </th>
            <th>
                Total Jobs Found
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model.ListJob)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpCategory)
                    </td>
                    <td>
                        @if(item.TotalJobsByExpFound.Equals("0"))
                        {
                            @Model.TotalJobs
                        }else{
                             @Html.DisplayFor(modelItem => item.TotalJobsByExpFound)
                        }                    
                    </td>
                    <td>
                        <p id="btn-export">
                            <a href="@Url.ActionLink("ViewDetails","Spider", new { expCategory = @item.ExpCategory })" class="border border-dark btn btn-success"><i class="fa-solid fa-file-export"></i> Details </a>
                        </p>
                    </td>
                </tr>
           }
        }
    </tbody>
</table>